steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "docker.io/mesames/idm-vton-goog:v5"
      - "."
    env:
      - "DOCKER_BUILDKIT=1"

  # Step 2: Log in to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "login"
      - "-u"
      - "$_DOCKER_HUB_USERNAME"
      - "-p"
      - "$_DOCKER_HUB_TOKEN"

  # Step 3: Push the Docker image to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "docker.io/mesames/idm-vton-goog:v5"

