steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "docker.io/mesames/idm-vton-goog:usegoogle"
      - "."
    env:
      - "DOCKER_BUILDKIT=1"

  # Step 2: Log in to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$_DOCKER_PASSWORD" | docker login -u "$_DOCKER_USERNAME" --password-stdin

  # Step 3: Push the Docker image to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "docker.io/mesames/idm-vton-goog:usegoogle"

substitutions:
  _DOCKER_USERNAME: ""
  _DOCKER_PASSWORD: ""
